baseURL = "https://hemanth7787.github.io/knowmyphone_blog/"
title = "Know My Phone"

theme = "minimo"

googleAnalytics = ""
Paginate = 3

[params]
  description = "Know My Phone blog"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "KMP"
  copyrightStartYear = "2017"

[taxonomies]
  category = "categories"
  tag = "tags"

[author]
  name = "KMP staff"

[author.social]
  facebook = "."

[permalinks]
  page = "/:slug/"


# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
